/**
 * Generates a self-contained DevTools-console probe for the live chat sites.
 *
 * Selector drift is this project's recurring outage: the parsers lean on
 * Tailwind utility chains, and a spacing tweak on claude.ai / chatgpt.com /
 * gemini.google.com retires one without any visible change to the page. The
 * probe is how that gets diagnosed from outside a browser -- a maintainer (or
 * a user on a broken page) pastes it into the console and pastes the JSON back.
 *
 * The selector values are read from the parsers themselves rather than
 * transcribed, so the probe can never test a stale copy of them:
 *
 *   node scripts/selector-probe.mjs            # write dist-probe/selector-probe.js
 *   node scripts/selector-probe.mjs --stdout   # print it instead
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import ts from 'typescript';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const PLATFORMS = ['chatgpt', 'claude', 'gemini'];

/**
 * `selectors.ts` imports only `import type { SelectorSet }`, which
 * `transpileModule` erases along with the annotations -- so the transpiled
 * module has no runtime imports and loads straight off a data: URL. That is
 * the whole reason this reads the selector modules directly instead of
 * standing up a bundler: it holds only as long as they stay type-only, and
 * breaks loudly (an unresolved import) rather than silently if that changes.
 */
async function loadSelectors(platform) {
  const src = readFileSync(join(root, 'src/core/parsers', platform, 'selectors.ts'), 'utf-8');
  const js = ts.transpileModule(src, {
    compilerOptions: { module: ts.ModuleKind.ESNext, target: ts.ScriptTarget.ES2022 },
  }).outputText;
  const mod = await import(`data:text/javascript;base64,${Buffer.from(js).toString('base64')}`);
  const set = mod[`${platform.toUpperCase()}_SELECTORS`];
  const patterns = mod[`${platform.toUpperCase()}_URL_PATTERNS`];
  if (!set) throw new Error(`${platform}: no exported selector set`);
  return { set, patterns: (patterns ?? []).map(String) };
}

/** Flatten `{a, custom: {b}}` into `{a, 'custom.b'}` -- the probe's report keys. */
function flatten(set) {
  const out = {};
  for (const [key, value] of Object.entries(set)) {
    if (key === 'custom' && value && typeof value === 'object') {
      for (const [ck, cv] of Object.entries(value)) out[`custom.${ck}`] = cv;
    } else if (typeof value === 'string') {
      out[key] = value;
    }
  }
  return out;
}

const table = {};
for (const platform of PLATFORMS) {
  const { set, patterns } = await loadSelectors(platform);
  table[platform] = { patterns, selectors: flatten(set) };
}

const probe = `/* ai-chat-exporter selector probe -- generated by scripts/selector-probe.mjs.
   Open the chat page you are exporting, paste this into the DevTools console,
   then copy the JSON it prints. It reports selector match counts and class
   names only -- never message text. */
(() => {
  const TABLE = ${JSON.stringify(table, null, 2)};
  const href = location.href;
  const platform = Object.keys(TABLE).find((p) =>
    TABLE[p].patterns.some((re) => new RegExp(re.replace(/^\\/|\\/[a-z]*$/g, '')).test(href))
  );
  if (!platform) {
    // Only the host: a full href carries the conversation id (and any query
    // or fragment) into output the user is invited to paste into an issue.
    console.log('No parser claims this page. Host:', location.hostname);
    return;
  }
  const selectors = TABLE[platform].selectors;
  const counts = {};
  const dead = [];
  for (const [key, sel] of Object.entries(selectors)) {
    let n;
    try {
      n = document.querySelectorAll(sel).length;
    } catch (e) {
      n = 'INVALID: ' + e.message;
    }
    counts[key] = n;
    if (n === 0) dead.push(key);
  }

  /* When a selector is dead the useful evidence is what the page renders
     *instead*, so the report carries a census of the classes actually in use
     on the plausible containers plus the data-* attribute names present. Both
     are structural: no message text crosses into the report. */
  const scrollers = [...document.querySelectorAll('div')]
    .filter((el) => {
      const o = getComputedStyle(el).overflowY;
      return (o === 'auto' || o === 'scroll') && el.scrollHeight > el.clientHeight + 40;
    })
    .slice(0, 8)
    .map((el) => ({ class: el.className, children: el.childElementCount }));

  const dataAttrs = {};
  for (const el of document.querySelectorAll('*')) {
    for (const name of el.getAttributeNames()) {
      if (name.startsWith('data-')) dataAttrs[name] = (dataAttrs[name] ?? 0) + 1;
    }
  }

  const report = {
    probe: 1,
    platform,
    url: location.origin + location.pathname.replace(/[0-9a-f-]{16,}/gi, ':id'),
    lang: document.documentElement.lang,
    counts,
    dead,
    scrollContainers: scrollers,
    dataAttributes: Object.fromEntries(
      Object.entries(dataAttrs).sort((a, b) => b[1] - a[1]).slice(0, 40)
    ),
  };
  console.log(JSON.stringify(report, null, 2));
  try {
    copy(JSON.stringify(report));
    console.log('%cCopied to clipboard.', 'color:green');
  } catch {}
  return report;
})();
`;

if (process.argv.includes('--stdout')) {
  process.stdout.write(probe);
} else {
  mkdirSync(join(root, 'dist-probe'), { recursive: true });
  const out = join(root, 'dist-probe/selector-probe.js');
  writeFileSync(out, probe);
  console.log(`wrote ${out} (${probe.length} bytes)`);
}
